[project]
name = "p1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.0.0,<2.0.0",
    "pandas>=1.3.5,<2.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
